# Generated by Django 5.2.4 on 2025-08-04 09:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image", models.ImageField(upload_to="images/")),
                (
                    "watermarked_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="watermarked_images/"
                    ),
                ),
                ("secret_message", models.TextField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_index",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "blockchain_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["block_index"], name="converter_i_block_i_301557_idx"
                    ),
                    models.Index(
                        fields=["blockchain_hash"],
                        name="converter_i_blockch_664abf_idx",
                    ),
                ],
            },
        ),
    ]
