# Generated by Django 5.2.4 on 2025-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='watermarked_images/'),
        ),
    ]
